### ISSUE TITLE
Bower integration

### ISSUE THREAD

**Issue by warapitiya** [mmautomatizacion/angular-fullpage.js#1]
Really like to see the native support methods and organized configurations. It would really helpful if you add Bower support.

**Comment by mmautomatizacion** [comment]
Thanks for the comments, and sorry for the delay in answering. I will try to integrate with bower in a few days.

**Comment by Dzeg** [comment]
Excelente! estare esperando cuando lo tengas integrado a bower.!! buen trabajo, estoy empezando a probarlo y hasta el momento lo veo bastante bien. good work! if for some reason you cannot speak/read spanish lol

**Comment by mmautomatizacion** [comment]
Muchas gracias @Dzeg!
Añadida compatibilidad con Bower. Pruébala y me cuentas ;)

**Comment by warapitiya** [comment]
@mmautomatizacion I would say we need to push this to NPM first. No one use Bower now.

**Comment by mmautomatizacion** [comment]
You have compatibility with NPM too. Try it! I will be waiting for feedback.
