### ISSUE TITLE
fp-afterSlideLoad is missing

### ISSUE THREAD

**Issue by benjamindamm** [mmautomatizacion/angular-fullpage.js#10]
Hello me again ;)

I found that you missed to call the fp-afterSlideLoad Event

So i added on line to your `function afterSlideLoads(v)`

`$rootScope.$emit('fp-afterSlideLoad', {anchorLink: v.slideAnchor, index: v.sectionIndex, slideAnchor: v.slideAnchor, slideIndex: v.slideIndex})`

**Comment by mmautomatizacion** [comment]
I will check. Thanks!!

**Comment by mmautomatizacion** [comment]
Solved in new release, 1.3.7.

Thanks!
