### ISSUE TITLE
Can you share the example snippet to create a link where I can click and move to that slide/section?

### ISSUE THREAD

**Issue by kutec** [mmautomatizacion/angular-fullpage.js#11]
Hello,

I was trying to implement FullpageJs with AngularJS + Liferay. I am not getting how to implement link sections, where I can click and navigate to relevant section or slide.

If anyone can share example snippet, it would be appreciated.

```
<div class="col-md-3 hidden-sm hidden-xs">
        <ul id="myMenu" class="section-links">
		<li data-menuanchor="firstPage" class="active"><a href="#firstPage">First section</a></li>
		<li data-menuanchor="secondPage"><a href="#secondPage">Second section</a></li>
		<li data-menuanchor="thirdPage"><a href="#thirdPage">Third section</a></li>
		<li data-menuanchor="fourthPage"><a href="#fourthPage">Fourth section</a></li>
	</ul>
</div>

<div class="col-md-9 col-sm-12 col-xs-12">
    <div full-page>
        <div class="section">Section 1</div>
        <div class="section">Section 2</div>
    </div>
</div>
```

Thanks,

**Comment by mmautomatizacion** [comment]
Hi,
Try to change `href="#firstPage"` to `ng-href="#!firstPage"`.

Don't forget to define the anchor name's.

You can check this at readme. And you have a example on our business website, [mmautomatizacion.com](http://mmautomatizacion.com), analyzing the code.

I hope I have been able to help.

**Comment by kutec** [comment]
I tried that. Didn't work :(

**Comment by mmautomatizacion** [comment]
Can you paste the code? And check the console error.

**Comment by kutec** [comment]
I am infect using `$locationProvider.html5Mode`

**Comment by mmautomatizacion** [comment]
Can you paste your code? I can't help you if I don't have more information.
