### ISSUE TITLE
state change issue

### ISSUE THREAD

**Issue by kukac7** [mmautomatizacion/angular-fullpage.js#14]
it will not be destroy when the state is changed.
(and initialization when the state is re-activated.)
i do not care about anchoring and linking.
please have a solution.
yes, i read that it is not supported now. 😞

**Comment by mmautomatizacion** [comment]
Hi kukac7,
I don't understand the problem exactly. Can you give me more information about it? I will try to help you.

**Comment by kukac7** [comment]
ui-router + html5 mode -> state change -> fullpage.js still init (body class, etc.) -> go back to the state with fullpage.js -> destroy fullpage.js

[example](https://embed.plnkr.co/z81imqSXTFQuiGVXtFRJ/)

**Comment by mmautomatizacion** [comment]
You can't use a router with fullPage. Sorry.

**Comment by kukac7** [comment]
yes, i know that.
but it would be good to solve this.
so i was forced to use it as a directive.
which is not so nice solution.

**Comment by mmautomatizacion** [comment]
It's not an issue to resolve. FullPage use his own routing method. It have to load all the pages completely for a smooth slide effect. If you use FullPage and ui-router, both will change the url/hash.
