### ISSUE TITLE
Not working with WebPack

### ISSUE THREAD

**Issue by Gusi** [mmautomatizacion/angular-fullpage.js#7]
For webpack to work, you must include src folder, or change the "main" entry in package.json

`  "main": "dist/mm.angular-fullpage.min.js",`

**Comment by mmautomatizacion** [comment]
I've never used WebPack, but What's exactly the problem? I think WebPack will use the source file, placed in `src` forlder, for generate one only file for all.

**Comment by Gusi** [comment]
Webpack uses the "main" entry in the package.json to upload the file. Right now the main points to a file that doesn't exist (src/mm-angular-fullpage.js) because the src folder is not included in the npm distribution (and also the file name is wrong because of "-" instead of "."), so it doesn't work.

**Comment by mmautomatizacion** [comment]
Solved in last release, 1.3.5. Thanks for your notice.
