### ISSUE TITLE
sections.filter is not a function

### ISSUE THREAD

**Issue by balazs-guti** [mmautomatizacion/angular-fullpage.js#9]
Hi,
Any ideas why I get this error?
I have everything included, should be fine I think.
![mm-fullpage-bug](https://cloud.githubusercontent.com/assets/17123843/23961810/5f7fc15c-09ac-11e7-9629-5a0df1480ece.jpg)

**Comment by balazs-guti** [comment]
after adding fullPageConfigProvider with the default options (mentioned in readme) I have this error
![mm-fullpage-bug2](https://cloud.githubusercontent.com/assets/17123843/23962941/ff4007f8-09af-11e7-89c9-7dc3212fc27b.jpg)

**Comment by mmautomatizacion** [comment]
Have you included jQuery library?

**Comment by balazs-guti** [comment]
Yes I have, and it's included before the plugin.
![mm-fullpage-bug3](https://cloud.githubusercontent.com/assets/17123843/24008411/d6a9d04a-0a71-11e7-9930-76b3fb5cf473.jpg)

**Comment by mmautomatizacion** [comment]
Ok. Can you try to get the value of "sections" variable in 'setOptionsFromDOM' function? Maybe it's empty or not an array. You can try to execute the 'find' and 'filter' methods for any array too for check jQuery is working correctly.

**Comment by Domanskiy** [comment]
@balazs-guti, seems like it's file order problem. Try to include jquery first! It should help.
@mmautomatizacion could you add jquery as a dependency for npm and bower packages, please?

**Comment by mmautomatizacion** [comment]
@balazs-guti check the order of file inject. jQuery must be before mm.angular-fullpage.js.

@Domanskiy, I just added jQuery dependency for NPM and Bower. Thanks for advice.
